# Generated by Django 5.0.3 on 2024-03-28 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organisation_directors', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('employees', models.ManyToManyField(null=True, related_name='organisation_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организациb',
                'ordering': ['name'],
            },
        ),
    ]
