# Generated by Django 5.0.3 on 2024-04-04 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod')),
                ('name', models.CharField(max_length=32, verbose_name='Назапние')),
                ('sort', models.PositiveSmallIntegerField(verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус обеда',
                'verbose_name_plural': 'Статусы обеды',
            },
        ),
        migrations.CreateModel(
            name='ReplacementStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod')),
                ('name', models.CharField(max_length=32, verbose_name='Назапние')),
                ('sort', models.PositiveSmallIntegerField(verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус смены',
                'verbose_name_plural': 'Статусы смены',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organisation_directors', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('employees', models.ManyToManyField(blank=True, related_name='organisation_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('min_active', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальное количество активных сотрудников')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальная длительность обеда')),
                ('employees', models.ManyToManyField(blank=True, related_name='group_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_managers', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='breaks.organisation', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('break_start', models.TimeField(verbose_name='Начало обеда')),
                ('break_end', models.TimeField(verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(verbose_name='Максимальное продолжительност обеда')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='breaks.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='breaks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='breaks', to='breaks.breakstatus', verbose_name='Статус')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='breaks.replacement', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Обеденный перерыв',
                'verbose_name_plural': 'Обеденный перерывы',
                'ordering': ['-replacement__date', 'break_start'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to=settings.AUTH_USER_MODEL, verbose_name='Cотрудники')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='breaks.replacement', verbose_name='Смена')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='replacement_employees', to='breaks.replacementstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Смена - Работник',
                'verbose_name_plural': 'Смены - Работники',
            },
        ),
    ]
