# Generated by Django 5.0.3 on 2024-03-29 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_alter_organisation_options_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('break_start', models.TimeField(verbose_name='Начало обеда')),
                ('break_end', models.TimeField(verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(verbose_name='Максимальное продолжительност обеда')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='breaks.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date',),
            },
        ),
    ]
