# Generated by Django 5.0.3 on 2024-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0004_replacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod')),
                ('name', models.CharField(max_length=32, verbose_name='Назапние')),
                ('sort', models.PositiveSmallIntegerField(max_length=32, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус смены',
                'verbose_name_plural': 'Статусы смены',
                'ordering': ('sort',),
            },
        ),
    ]
