# Generated by Django 5.0.3 on 2024-03-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0006_replacementemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementstatus',
            name='sort',
            field=models.PositiveSmallIntegerField(verbose_name='Сортировка'),
        ),
    ]
