# Generated by Django 5.0.3 on 2024-04-01 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0007_alter_replacementstatus_sort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreaktStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Kod')),
                ('name', models.CharField(max_length=32, verbose_name='Назапние')),
                ('sort', models.PositiveSmallIntegerField(verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус обеда',
                'verbose_name_plural': 'Статусы обеды',
            },
        ),
        migrations.AlterModelOptions(
            name='replacementstatus',
            options={'verbose_name': 'Статус смены', 'verbose_name_plural': 'Статусы смены'},
        ),
        migrations.AlterField(
            model_name='replacementemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to=settings.AUTH_USER_MODEL, verbose_name='Cотрудники'),
        ),
    ]
