# Generated by Django 5.0.3 on 2024-04-01 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0008_breaktstatus_alter_replacementstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreaktStatus',
            new_name='BreakStatus',
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность обеда')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='breaks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='breaks.replacement', verbose_name='Смена')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='breaks', to='breaks.breakstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обед',
                'verbose_name_plural': 'Обеды',
                'ordering': ['-replacement__date', 'break_start'],
            },
        ),
    ]
