# Generated by Django 5.0.3 on 2024-04-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0010_alter_break_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='duration',
        ),
    ]
